name:                Relcode-hs
github:              "githubuser/Relcode-hs"
author:              "C Leon M Petersson"
maintainer:          "leon.petersson@fysik.su.se"

description:         Interpret output from relcode.

dependencies:
- base           >= 4.7.0  && < 5.0
- composition    >= 1.0.2  && < 1.1
- containers     >= 0.6.7  && < 0.7
- directory      >= 1.3.7  && < 1.4
- extra          >= 1.7.14 && < 1.8
- filepath       >= 1.4.2  && < 1.5
- gamma          >= 0.10.0 && < 0.11
- ghc            >= 9.4.6  && < 9.5
- lens           >= 5.2.3  && < 5.3
- mtl            >= 2.2.2  && < 2.3
- safe           >= 0.3.19 && < 0.4
- split          >= 0.2.3  && < 0.3
- utility-ht     >= 0.0.17 && < 0.1
- wigner-symbols >= 1.0.0  && < 1.1
- yjtools        >= 0.9.18 && < 1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src/hs/

executables:
  Relcode.x:
    main:                Relcode.hs
    source-dirs:         app/hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Relcode-hs
